### ISSUE TITLE
Best way to handle a flexible array?

### ISSUE THREAD

**Issue by steveerhart** [TaylanUB/scheme-bytestructures#21]
What would be the best way to describe and handle something like

`struct double_vector_st {
    size_t length;
    double array[];
};`

**Comment by mwette** [comment]
> On Sep 15, 2017, at 8:43 AM, Steve <notifications@github.com> wrote:
> 
> What would be the best way to describe and handle something like
> 
> struct double_vector_st { size_t length; double array[]; };
> 


(bs:struct (list `(length ,size_t) `(array ,(bs:vector 0 double)))

**Comment by steveerhart** [comment]
I won't be able to index into the 0 length vector though, correct?

How would I get to the bytevector that "array" is supposed to contain once I get the length?

**Comment by mwette** [comment]
I don't know how bs:vector is implemented, but it would be nice if it declaration with "0" nicely.   That is, when set! to a vector of any length it allows referencing into that vector.  But ...
```> (use-modules (bytestructures guile))
> (define vec (bs:vector 0 double))
> (define v3 (bytestructure vec #(1.0 2.0 3.0)))
.../numeric.scm:66:0: In procedure setter:
.../numeric.scm:66:0: In procedure bv-f6-set!: Value out of range: 0
```
I think it should be able to deal with ``[]``.

**Comment by TaylanUB** [comment]
I tried to respond to this thread via my phone the other day. Looks like it didn't come through. Sorry about the delay. Here's the original message:

On Sep 15, 2017 5:51 PM, mwette <notifications@github.com> wrote:
>
>
> > On Sep 15, 2017, at 8:43 AM, Steve <notifications@github.com> wrote:
> > 
> > What would be the best way to describe and handle something like
> > 
> > struct double_vector_st { size_t length; double array[]; };
> > 
>
>
> (bs:struct (list `(length ,size_t) `(array ,(bs:vector 0 double)))
>

The problem is that this won't allow accessing the array's contents, whereas in C it's no problem.

There has long been support for "dynamic" bytestructure descriptors whose behavior depends on the contents of the bytevector they govern over at run time, but the standard descriptors in the library don't support this for practical reasons...

I'm afraid the only way is to use a throwaway descriptor first (like the one mwette wrote, then create a descriptor with the correct array length at run time, by reading the length field via the throwaway descriptor.

Maybe you'll find a nice abstraction to make this easier.

Interesting would be if Guile provided "open ended" bytevectors so that arbitrary indices can be used without raising an 'index out of bounds' exception, at risk of causing a segfault in case the accessed memory region is not readable. That would make this
use-case as easy as it is in C.

HTH,
Taylan

**Comment by steveerhart** [comment]
Thanks for the help, guys. I was hoping to avoid the throw away descriptor
route, but I guess I can't.

You can close this issue if you'd like.
