### ISSUE TITLE
Field offset miscalculation on i686

### ISSUE THREAD

**Issue by civodul** [TaylanUB/scheme-bytestructures#30]
Hello,

Guile-Git has a `%diff-delta` bytestructure for which field offset is miscalculated on i686.  It is a structure whose fields are structures themselves, and is defined as follows:

```scheme
(define %diff-delta
  (bs:struct `((status ,int)
               (flags ,uint32)
               (similarity ,uint16)
               (nfiles ,uint16)
               (old-file ,%diff-file)
               (new-file ,%diff-file))))
```

where `%diff-file` is also a bytestructure.  It goes like this:

```scheme
scheme@(git structs)> ,use(bytestructures guile ffi)
scheme@(git structs)> (bytestructure-descriptor->ffi-descriptor %diff-delta)
$6 = (8 7 5 5 ((3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3) * 10 7 5 5) ((3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3) * 10 7 5 5))
```

Unfortunately I wasn't able to poke at the offset calculations in scheme-bytestructures so I cannot give a more precise report.  The code is at https://gitlab.com/guile-git/guile-git/blob/master/git/structs.scm#L165 .  Running `make check` on i686 triggers the crash.

Let me know if I can help!

Ludo'.

**Comment by TaylanUB** [comment]
Hidy. First things first: Does this happen using Bytestructures 1.0.1? That one fixed an issue like this.

**Comment by TaylanUB** [comment]
Actually nevermind that. That issue seems unrelated.

I don't have access to an i686 system. If the bug can't be reproduced on x86_64, you'll have to help me a bit.

I would start by verifying the following expectations, in this oder (you can bail out as soon as one isn't met), on an i686 system:
- In C, `sizeof(git_diff_file)` gives 40.
- In C, `sizeof(git_diff_delta)` gives 96.
- In Guile, `(bytestructure-descriptor-size %diff-file)` gives 40.
- In Guile, `(bytestructure-descriptor-size %diff-delta)` gives 96.

If the sizes are correct, it would be a nasty coincidence for the offsets within not to be.

Pondering on the issue a bit, my best guess is that 32-bit systems don't ever pad to multiples of more than 32 bits, even if a type is bigger than 32 bits (or a struct contains a type bigger than 32 bits). This would mean that `git_diff_file` is padded to multiples of 32 bits and not 64. **That would mean that `sizeof(git_diff_delta)` will give 92 not 96.** If that guess is correct, I know what to do. Let's see. :-)

**Comment by civodul** [comment]
TaylanUB <notifications@github.com> skribis:

> Pondering on the issue a bit, my best guess is that 32-bit systems don't ever pad to multiples of more than 32 bits, even if a type is bigger than 32 bits (or a struct contains a type bigger than 32 bits). This would mean that `git_diff_file` is padded to multiples of 32 bits and not 64. **That would mean that `sizeof(git_diff_delta)` will give 92 not 96.** If that guess is correct, I know what to do. Let's see. :-)

Right, the SysV ABI says that:

  Aggregates (structures and arrays) and unions assume the alignment of
  their most strictly aligned component.

That could well be the problem.

Is there a way to view the computed field offsets and alignment?

Ludo’.

**Comment by TaylanUB** [comment]
>Is there a way to view the computed field offsets and alignment?

There is, though a bit hacky:

```scheme
(define da (@@ (bytestructures guile struct) debug-alignment))

(da <pack> <fields>)  ;#f for default packing
                      ;<fields> is like the bs:struct argument e.g. `((x ,uint8) (y ,uint16))
```

That will output something like:

```
{
    0: field1:8
    16: field2:16
}
```

The number at the start of the line is the offset, after which the name of the field and its size appear. (All in bits, because bitfields are supported too.)
In my example here we see that `field2` was positioned at 16 even though field1 only takes 8 bits of space. That's because field2 has an alignment of 16 bits. Most numeric types have an alignment equal to their size, though I suppose it caps at the CPU's word size...

Actually, gimme a sec and I'll improve that output format to include the alignment value explicitly.

**Comment by TaylanUB** [comment]
I just pushed a commit that caps the alignment of numeric types at the CPU word size. So a 64-bit integer will be aligned at 32 bits if on a 32-bit architecture. (This implicitly affects structs and unions as well.)

Could you test if it works on i686?

**Comment by civodul** [comment]
TaylanUB <notifications@github.com> skribis:

> I just pushed a commit that caps the alignment of numeric types at the CPU word size. So a 64-bit integer will be aligned at 32 bits if on a 32-bit architecture. (This implicitly affects structs and unions as well.)

I think you should check exactly what the SysV ABI says.  What you
describe above sounds good, but I wonder if there are corner cases where
it’s not that simple.

Ludo’.

**Comment by TaylanUB** [comment]
You're right. I googled a bit and found this abi386 documentation, which I suppose applies to i686 as well.

https://www.uclibc.org/docs/psABI-i386.pdf

This seems to confirm that alignment is mostly capped at the word size. There are some exceptions (like `long long` and `long double`), but they are not supported by bytestructures yet. I also checked the amd64 ABI and it's a similar situation there. I'll need to restructure the code a bit in the future to add those types with alignment greater than the word size, but for now this should behave correctly I believe.

If guile-git's `make check` succeeds on i686 when using the current HEAD of bytestructure's master branch, I'll make this the 1.0.2 release. Thanks for the report & the help. :-)


For those interested, a relevant bug report in Rust:
https://github.com/rust-lang/rust/issues/43899

**Comment by civodul** [comment]
> If guile-git's `make check` succeeds on i686 when using the current HEAD of bytestructure's master branch, I'll make this the 1.0.2 release. Thanks for the report & the help. :-)

I just tested it and it works like a charm on i686, x86_64, and aarch64,
thanks!

Now Guile-Git’s `make check` still segfaults on ARMv7 (32-bit, “hard
float” ABI).  Unfortunately `debug-alignment` isn’t really helpful in
displaying info for that `%diff-delta` bytestructure.  What would you
suggest?

Ludo’.

**Comment by civodul** [comment]
Looks like we're all set!  I successfully ran Guile-Git's `make check` with commit b4ba74751bfcead99b7fc824e3a1bffeb04293cc on x86_64, i686, armhf, and aarch64.

Thank you!

**Comment by TaylanUB** [comment]
Thank you for the help. :-)
I'll release 1.0.2 shortly.

**Comment by civodul** [comment]
Hello Taylan!

Looks like 1.0.2 hasn't happened yet.  :-)  Could you tag it?

TIA!
Ludo'.

**Comment by TaylanUB** [comment]
All done now, thanks for the heads-up.

**Comment by civodul** [comment]
Awesome!  I notice a build failulre though:

```
Syntax error:
bytestructures/guile/struct.scm:10:19: include-from-path: file not found in path in subform "bytestructures/body/align.scm" of (include-from-path "bytestructures/body/align.scm")
make: *** [Makefile:762: bytestructures/guile.go] Error 1
```

Am I missing something?

**Comment by TaylanUB** [comment]
Embarrassing! The file was missing in Makefile.am and I didn't notice because I didn't isolate the build environment for the tarball.

1.0.3 is out.

**Comment by civodul** [comment]
That was fast!

Tested on i686, x86_64, ARMv7, and aarch64, with Guile 2.2 and 2.0, and
Guile-Git’s test suite passes everywhere.  Thanks again!

**Comment by TaylanUB** [comment]
It's my compensation for not being around to help with other things. ;-)

Thanks for the feedback!
