### ISSUE TITLE
bytestructure-ref with one arg undefined?

### ISSUE THREAD

**Issue by mwette** [TaylanUB/scheme-bytestructures#31]
If I execute bytestructure-ref with only a bytestructure arg I get something I can't make sense of.
Should this be an error?  Maybe it could return the underlying bytevector?
```
scheme@(guile-user)> (use-modules (bytestructures guile))
scheme@(guile-user)> (define struc (bs:struct `((a ,int) (b ,double))))
scheme@(guile-user)> struc
$1 = #<bytestructure-descriptor 0x1edb300>
scheme@(guile-user)> (define val (bytestructure struc))
scheme@(guile-user)> val
$2 = #<bytestructure 0x1e962d0>
scheme@(guile-user)> (bytestructure-ref val)
$3 = #<bytestructure 0x1c986f0>
```

**Comment by TaylanUB** [comment]
It's a feature, not a bug. ;-)

As the (somewhat complicated) documentation of `bytestructure-ref` explains, it "traverses" through a bytestructure with the given indices (using `bytestructure-unwrap`) then either uses the `getter` procedure of the ultimate descriptor to actually acquire a "primitive" value, or if the `getter` procedure is `#f` then it returns a new bytestructure which encapsulates the position that was reached in the traversal.

Practical example: if you have a vector of structs, and you use `bytestructure-ref` with only an integer index (i.e. an index into the vector) but don't provide a struct field, you'll get a bytestructure that encapsulates the corresponding struct within the vector. You could then call `bytestructure-ref` on that result, with only a struct field as an index, to get a field of that struct.

So what happens in this case: No indices are provided at all, meaning the same bytestructure is returned. Due to implementation complexities however, a new bytestructure with the same information is allocated, hence the different memory address...

It's admittedly confusing, but in a way it's quite logical and consistent. I would rather not special-case the zero-indices case in `bytestructure-ref` (nor in `bytestructure-unwrap`). What do you say?

**Comment by mwette** [comment]
Just asking.  I would suggest  perhaps to add documentation that "the gist of the above is that if no reference arguements are provided ..."

**Comment by TaylanUB** [comment]
You're right, I added a clarifying paragraph to that effect.
