### ISSUE TITLE
tarball could use some config help

### ISSUE THREAD

**Issue by mwette** [TaylanUB/scheme-bytestructures#38]
I ran autoconf on the tarball release (*-1.0.7.tar.gz) and got this:
```
configure.ac:4: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:7: error: possibly undefined macro: AM_SILENT_RULES
mwette$ pwd
/var/tmp/mwette/scheme-bytestructures-1.0.7
```
Is that what I should use?   When I ran it again it worked.  Go figure.
Then I ran configure and got 
```
mwette$ ./configure
./configure: line 1681: syntax error near unexpected token `-Wall'
./configure: line 1681: `AM_INIT_AUTOMAKE(-Wall -Werror foreign color-tests)'
```
Not sure what you are expecting.

Also, I think you may need to update to guile.m4 from 2.9.8 so that it will build.

**Comment by TaylanUB** [comment]
Ah dang, I haven't even created a release tarball (`make dist`) for this release, have I?

Thanks for the heads up, I'll look into it ASAP.

**Comment by TaylanUB** [comment]
Hmm, I haven't had the problem you mention using the following sequence:

    $ autoreconf -fi
    $ ./configure --prefix=/usr/local
    (manually fix a small issue in the generated Makefile)
    $ make
    $ make dist

I've had a different problem, probably due to the fact I'm currently on an old system with guile-2.0 (not even guile-2.2), where the ./configure script couldn't detect guild, guile-config and guile-tools, but when I added them manually to the generated Makefile, the rest worked fine.

**Comment by TaylanUB** [comment]
I've now uploaded a release tarball. Could you please try "./configure && make" with it?

**Comment by mwette** [comment]
in 1.0.7 tarball, ./configure works fine, but make does not work on my system (Ubuntu 18.04) because Ubuntu for some reason installs guile-2.2 but not guild-3.3, so in the Makefile GUILE is defined but not GUILD and I can't seem to over right the definition of GUILE or GUILD.   This may be a guile issue.

In nyacc, I have included guild.in and use that to get around my problem.

But thanks for the tarball, at least configure is working nominally.

**Comment by mwette** [comment]
in my configure.ac I use
```
AC_ARG_VAR([GUILE],[path to guile binary])
```
to allow overriding GUILE (for GUILD I use my own guild from guild.in)

**Comment by TaylanUB** [comment]
What you had on Ubuntu seems to be the same problem as what I had. I don't remember ever facing such an issue on Debian or Guix so maybe the Guile package for Ubuntu somehow causes it. I noticed that it installs `/usr/bin/guile-2.0` then links to it from `/usr/bin/guile` but it does no such thing for `/usr/bin/guild-2.0` or the other binaries that `./configure` fails to find...

Not sure if I'll have time to investigate, since I don't use Ubuntu much.
