### ISSUE TITLE
support for anonymous unions in structs

### ISSUE THREAD

**Issue by mwette** [TaylanUB/scheme-bytestructures#43]
I ran into the following trying to provide FFI for liburing.
It would be nice if there was a way to support anonymous structs and unions.
```
;; struct io_uring_sqe {
;;   __u8 opcode; /* type of operation for this sqe */
;;   __u8 flags; /* IOSQE_ flags */
;;   __u16 ioprio; /* ioprio for the request */
;;   __s32 fd; /* file descriptor to do IO on */
;;   union {
;;     __u64 off; /* offset into file */
;;     __u64 addr2;
;;   };
;;   union {
;;     __u64 addr; /* pointer to buffer or iovecs */
;;     __u64 splice_off_in;
;;   };
;;   __u32 len; /* buffer size or number of iovecs */
...
```

**Comment by TaylanUB** [comment]
Interesting, I didn't know about this GCC/C11 feature.

Currently a `field-spec` in a struct/union definition must be a two- or three-element list where the first element is a symbol and the second is a bytestructure object.

I think `field-spec` could be expanded to allow special `struct` and `union` field types by reserving those symbols in the first position. To be backwards compatible / prevent silent breakage, the mechanism would only kick in if the second element is *not* a bytestructure but a list (see below). Otherwise it would use old behavior and maybe emit a warning.

Example of how `io_uring_sqe` could be represented:

```scheme
(define io-uring-sqe
  (bs:struct
    `((opcode           ,uint8)
      (flags            ,uint8)
      (ioprio           ,uint14)
      (fd               ,int32)
      (union
        ((off           ,uint64)
         (addr2         ,uint64)))
      (union
        ((addr          ,uint64)
         (splice_off_in ,uint64)))
      (len              ,uint32))))
```

Actually implementing this is left as an exercise to a future me who has time. ;-) Patches welcome too of course.

Sorry for not having responded to your other enhancement suggestions in ages by the way. I might just find some time in the next couple weeks and see if I can implement all your nice suggestions at once.

**Comment by TaylanUB** [comment]
I just implemented this. Please see if it works fine for you! Haven't made a release yet.

**Comment by TaylanUB** [comment]
Closing this since it's been released now.

**Comment by mwette** [comment]
added #62120 in https://savannah.nongnu.org/bugs/index.php to incorporate into nyacc
